### ISSUE TITLE
No valid game startup actions found.

### ISSUE THREAD

**Issue by jacket430** [CanRanBan/PlayniteExtension-Library-GooglePlayGames#2]
Hey there, just installed Play Games and your plugin on a fresh copy of Windows 11. I can launch the game normally but when I try to launch it through Playnite, I get a "No valid game startup actions found. When using emulator actions, make sure platform definitions match between the game and the emulator configuration." error. Not sure if this is something I'm doing wrong but I just imported the game like normally and tried to launch it to no avail.

**Comment by zbee** [comment]
Same issue here. [I see that according to the wiki](https://github.com/CanRanBan/PlayniteExtension-Library-GooglePlayGames/wiki) it should at least open Google Play Games, but it doesn't: just gives the error message above.

---

I did get it to open Google Play Games with this action, for any others wondering how to make use of this library importer.
> Play Action: Yes
> Type: File
> Path: C:\Program Files\Google\Play Games\Bootstrapper.exe

(this is the default install location)

**Comment by CanRanBan** [comment]
Regarding your comment about:
> Launch of "Google Play Games (Beta)" application.

The `3rd Party Clients` menu offering this is located in the main menu and the menu of the tray icon (if enabled).

---

At the time of writing the Wiki entry Google did not offer a possibility to directly start games externally without using fragile workarounds. I sent feedback to Google back then to hopefully get shortcuts or a similar feature allowing this. They added them multiple months later, see [Release notes for Google Play Games on PC](https://support.google.com/googleplay/answer/13585779?hl=en).

Excerpt of the release notes (`April 2024 Update`):
> Lets you create shortcuts for games on your desktop and in the Start menu

I did not implement any workarounds to start games before noticing this because of personal time limitations.

The update using launch parameters obtained from these shortcuts is still not finished because the emulator process is additionally used for the main window and not only for executing games. This complicates game time tracking and I want to provide proper tracking.

Two possibilities could be used for time tracking:
- waiting on all emulator processes to exit which requires to close the main window to tray or
- checking if the game window is still open with a delay between two consecutive checks.

I personally prefer the second option because it is more accurate than waiting an arbitrary time for the emulator process to exit (which would additionally never happen as long as the main window is open).

**Comment by CanRanBan** [comment]
Update is now live with [v0.2.0](https://github.com/CanRanBan/PlayniteExtension-Library-GooglePlayGames/releases/tag/v0.2.0).
